# Generated by usvc-1.14.4
# Feel free to adjust, it will not be overridden

defmodule GrpcMock.Mixfile do
  use Mix.Project

  @version (case File.read("VERSION") do
              {:ok, version} -> String.trim(version)
              {:error, _} -> "0.0.0-development"
            end)

  def project do
    [
      app: :grpc_mock,
      version: @version,
      elixir: "~> 1.6",
      build_embedded: Mix.env() == :prod,
      start_permanent: Mix.env() == :prod,
      elixirc_paths: elixirc_paths(Mix.env()),
      description: description(),
      package: package(),
      docs: docs(),
      deps: deps(),
      name: "GrpcMock",
      homepage_url: "https://github.com/coingaming/grpc-mock/tree/v#{@version}"
    ]
  end

  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger], mod: {GrpcMock.Application, []}]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp description do
    """
    GrpcMock is mocking library for [Elixir gRPC implementation](https://github.com/tony612/grpc-elixir).
    It provides seamless mock creation based on `pb.ex` definition and
    usual mocking "expect" - "verify" mechanisms.
    """
  end

  defp package do
    [
      organization: "coingaming",
      maintainers: ["Predrag Rakic"],
      licenses: ["Apache License, Version 2.0"],
      files: ["lib", "mix.exs", "README.md", "CHANGELOG.md", "VERSION"],
      links: %{"GitHub" => "https://github.com/coingaming/grpc-mock/tree/v#{@version}"}
    ]
  end

  defp docs do
    [
      main: "GrpcMock",
      source_ref: "v#{@version}",
      source_url: "https://github.com/renderedtext/grpc-mock"
    ]
  end

  defp deps do
    [
      {:credo, "~> 1.0", only: [:dev, :test], runtime: false},
      {:grpc, "~> 0.5", organization: "coingaming"},
      {:ex_doc, "~> 0.18.0", only: [:dev, :test]}
    ]
  end
end
